$pdf_mode = 1;
$interaction = 'nonstopmode';
$synctex = 1;

add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');
add_cus_dep('acn', 'acr', 0, 'run_makeglossaries');
sub run_makeglossaries {
    my ($base_name, $path) = fileparse($_[0]);
    return system "makeglossaries", "-d", $path, $base_name;
}